#!/bin/sh
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Haproxy init.d script for Ubuntu or other *nix.
# Description:       Haproxy init.d script for Ubuntu or other *nix.
### END INIT INFO
#
# custom haproxy init.d script, by Mattias Geniar
# Modified by Rico Sta. Cruz for Server Wizard
#
# chkconfig: 345 55 45
# description: haproxy is a TCP loadbalancer
# probe: true

HAPROXY_CONF=/etc/haproxy/haproxy.cfg
HAPROXY_BIN=/usr/local/sbin/haproxy
HAPROXY_PID=/var/run/haproxy.pid

[ -f $HAPROXY_BIN ] || exit 0
[ -f $HAPROXY_CONF ] || exit 0

# Define our actions
checkconfig() {
    # Check the config file for errors
    $HAPROXY_BIN -c -q -f $HAPROXY_CONF
    if [ $? -ne 0 ]; then
        echo "Errors found in configuration file."
        return 1
    fi

    return 0
}

start() {
    checkconfig || return 1

    echo -n "Starting HAProxy: "
    $HAPROXY_BIN -D -f $HAPROXY_CONF -p $HAPROXY_PID

    RETVAL=$?
    echo

    #[ $RETVAL -eq 0 ] && touch /var/lock/subsys/haproxy
    return $RETVAL
}

stop() {
    echo -n "Shutting down HAProxy: "
    kill -USR1 $(cat $HAPROXY_PID) || killall -USR1 haproxy

    RETVAL=$?
    echo

    #[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/haproxy
    [ $RETVAL -eq 0 ] && rm -f $HAPROXY_PID
    return $RETVAL
}

restart() {
    checkconfig || return 1
    stop
    start
}

check() {
      $HAPROXY_BIN -c -q -V -f $HAPROXY_CONF
}

reload() {
    checkconfig || return 1

    echo -n "Reloading HAProxy config: "
    $HAPROXY_BIN -f $HAPROXY_CONF -p $HAPROXY_PID -sf $(cat $HAPROXY_PID)

    success $"Reloading HAProxy config: "
    echo
}

# Possible parameters
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        rhstatus
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  checkconfig)
        check
        ;;
  *)
        echo "Usage: haproxy {start|stop|status|restart|reload|checkconfig}"
        exit 1
esac

exit 0
