echo "#user nobody;"
echo "worker_processes 1;"
echo "pid /var/run/nginx.pid;"
echo ""
echo "events {"
echo "    worker_connections 1024;"
echo "}"
echo ""
echo "http {"
echo "    passenger_root $PASSENGER_ROOT;"
echo "    passenger_ruby `which ruby`;"
echo "    passenger_max_pool_size 6;"
echo "    passenger_max_instances_per_app 0;"
echo "    "
echo "    include mime.types;"
echo "    default_type application/octet-stream;"
echo "    sendfile on;"
echo "    keepalive_timeout 65;"
echo "    "
echo "    include /opt/nginx/conf/conf.d/*.conf;"
echo "}"
